CREATE VIEW [viz].[early_warning_radar] AS
SELECT [fiscal_year]
      ,[fiscal_month]
      ,[fiscal_year_month]
      ,[fiscal_date]
      ,[Commodity]
      ,[category]
      ,[Sub-Category]
      ,[article]
      ,[vendor_name]
      ,[Brand_Name]
      ,[brand_category]
      ,[country_of_origin]
      ,[Index_Ticker]
      ,[commodity_value]
      ,[commodity_uom]
      ,[actual_cost]
      ,[should_cost]
      ,[forecast_anual_unit_volume]
      ,[po_cost]
      ,[exposure]
      ,[latest_change_fiscal_date]
      ,[latest_change_cv]
  FROM [viz].[tbl_early_warning_radar_app]

  UNION ALL

  SELECT [fiscal_year]
      ,[fiscal_month]
      ,[fiscal_year_month]
      ,[fiscal_date]
      ,[Commodity]
      ,[category]
      ,[Sub-Category]
      ,[article]
      ,[vendor_name]
      ,[Brand_Name]
      ,[brand_category]
      ,[country_of_origin]
      ,[Index_Ticker]
      ,[commodity_value]
      ,[commodity_uom]
      ,[actual_cost]
      ,[should_cost]
      ,[forecast_anual_unit_volume]
      ,[po_cost]
      ,[exposure]
      ,[latest_change_fiscal_date]
      ,[latest_change_cv]
  FROM [viz].[tbl_early_warning_radar_excel];