export const MapPolygonPointLineData = [
  {
    component_qty: 227,
    plant: 'plant_1',
    component_source: 'plant_19',
    latitude_supplier: 14.87319,
    latitude_plant: 40.7429,
    longitude_supplier: -92.3036,
    longitude_plant: -73.9928,
    plant_port_display_name: 'New York, USA, USNYC',
    plant_days_delayed: 4,
    plant_delay_category: '3 to 5 days delay',
    supplier_port_display_name: null,
    supplier_days_delayed: null,
    supplier_delay_category: null,
  },
  {
    component_qty: 1070,
    plant: 'plant_10',
    component_source: 'plant_19',
    latitude_supplier: 37.53918,
    latitude_plant: 29.16613,
    longitude_supplier: -77.44239,
    longitude_plant: 120.05544,
    plant_port_display_name: null,
    plant_days_delayed: null,
    plant_delay_category: null,
    supplier_port_display_name: null,
    supplier_days_delayed: null,
    supplier_delay_category: null,
  },
  {
    component_qty: 1075,
    plant: 'plant_2',
    component_source: 'plant_18',
    latitude_supplier: 29.6327,
    latitude_plant: 39.77401,
    longitude_supplier: -95.59774,
    longitude_plant: -104.97242,
    plant_port_display_name: null,
    plant_days_delayed: null,
    plant_delay_category: null,
    supplier_port_display_name: null,
    supplier_days_delayed: null,
    supplier_delay_category: null,
  },
  {
    component_qty: 904,
    plant: 'plant_21',
    component_source: 'plant_20',
    latitude_supplier: 34.22159,
    latitude_plant: 37.01565,
    longitude_supplier: -92.002,
    longitude_plant: -81.96925,
    plant_port_display_name: null,
    plant_days_delayed: null,
    plant_delay_category: null,
    supplier_port_display_name: null,
    supplier_days_delayed: null,
    supplier_delay_category: null,
  },
  {
    component_qty: 1050,
    plant: 'plant_22',
    component_source: 'plant_23',
    latitude_supplier: 35.15451,
    latitude_plant: 50.88189,
    longitude_supplier: -80.83039,
    longitude_plant: 4.44169,
    plant_port_display_name: null,
    plant_days_delayed: null,
    plant_delay_category: null,
    supplier_port_display_name: null,
    supplier_days_delayed: null,
    supplier_delay_category: null,
  },
  {
    component_qty: 380,
    plant: 'plant_3',
    component_source: 'plant_11',
    latitude_supplier: 29.75255,
    latitude_plant: 22.60053,
    longitude_supplier: -95.37224,
    longitude_plant: 120.30348,
    plant_port_display_name: 'Kaohsiung, Taiwan, TWKHH',
    plant_days_delayed: 1.47,
    plant_delay_category: 'Less than 3 days delay',
    supplier_port_display_name: 'Houston, USA, USHOU',
    supplier_days_delayed: 21,
    supplier_delay_category: 'More than 5 days delay',
  },
  {
    component_qty: 1150,
    plant: 'plant_4',
    component_source: 'plant_12',
    latitude_supplier: 40.78065,
    latitude_plant: 1.26154,
    longitude_supplier: -74.17402,
    longitude_plant: 103.7006,
    plant_port_display_name: 'Singapore, Singapore, SGSIN',
    plant_days_delayed: 0.71,
    plant_delay_category: 'Less than 3 days delay',
    supplier_port_display_name: 'Newark, New Jersey, USA, USCQE',
    supplier_days_delayed: 0.3,
    supplier_delay_category: 'Less than 3 days delay',
  },
  {
    component_qty: 1326,
    plant: 'plant_5',
    component_source: 'plant_13',
    latitude_supplier: -1.25813,
    latitude_plant: 49.27926,
    longitude_supplier: -48.45676,
    longitude_plant: -123.12302,
    plant_port_display_name: 'CAVAN , Vancouver, Canada, CAVAN',
    plant_days_delayed: 2.06,
    plant_delay_category: 'Less than 3 days delay',
    supplier_port_display_name: null,
    supplier_days_delayed: null,
    supplier_delay_category: null,
  },
  {
    component_qty: 152,
    plant: 'plant_6',
    component_source: 'plant_14',
    latitude_supplier: 48.63052,
    latitude_plant: 51.62263,
    longitude_supplier: 6.30301,
    longitude_plant: -2.8567,
    plant_port_display_name: null,
    plant_days_delayed: null,
    plant_delay_category: null,
    supplier_port_display_name: null,
    supplier_days_delayed: null,
    supplier_delay_category: null,
  },
  {
    component_qty: 644,
    plant: 'plant_7',
    component_source: 'plant_15',
    latitude_supplier: 43.49825,
    latitude_plant: 51.51878,
    longitude_supplier: 2.41352,
    longitude_plant: -0.08508,
    plant_port_display_name: null,
    plant_days_delayed: null,
    plant_delay_category: null,
    supplier_port_display_name: null,
    supplier_days_delayed: null,
    supplier_delay_category: null,
  },
  {
    component_qty: 332,
    plant: 'plant_8',
    component_source: 'plant_16',
    latitude_supplier: 42.491,
    latitude_plant: 37.63607,
    longitude_supplier: -71.12313,
    longitude_plant: -97.24271,
    plant_port_display_name: null,
    plant_days_delayed: null,
    plant_delay_category: null,
    supplier_port_display_name: 'Boston, USA, USBOS',
    supplier_days_delayed: 6,
    supplier_delay_category: 'More than 5 days delay',
  },
  {
    component_qty: 1125,
    plant: 'plant_9',
    component_source: 'plant_17',
    latitude_supplier: 51.51878,
    latitude_plant: 37.77377,
    longitude_supplier: -0.08508,
    longitude_plant: -122.4085,
    plant_port_display_name: null,
    plant_days_delayed: null,
    plant_delay_category: null,
    supplier_port_display_name: null,
    supplier_days_delayed: null,
    supplier_delay_category: null,
  },
]
