CREATE PROCEDURE [viz].[should_cost_analysis_tables_resfresh] as

TRUNCATE TABLE viz.tbl_should_cost_analysis_app;
INSERT INTO viz.tbl_should_cost_analysis_app (
[fiscal_year]
      ,[fiscal_month]
      ,[fiscal_date]
      ,[fiscal_year_month]
      ,[Commodity]
      ,[commodity_uom]
      ,[category]
      ,[Sub-Category]
      ,[article]
      ,[article_description]
      ,[Brand_Name]
      ,[material]
      ,[color]
      ,[Count]
      ,[size]
      ,[vendor_name]
      ,[Template_URL]
      ,[country_of_origin]
      ,[cost_category_group]
      ,[cost_category]
      ,[cost_element]
      ,[Index_Ticker]
      ,[actual_cost]
      ,[should_cost]
      ,[flag_modelled_cost]
      ,[funding_pct]
      ,[Sales Quantity]
      ,[Avg Unit Retail]
      ,[forecast_anual_unit_volume]
      ,[forecast_COGS]
      ,[forecast_revenue]
      ,[commodity_value]
	  ,filtering_id)

	SELECT[fiscal_year]
      ,[fiscal_month]
      ,[fiscal_date]
      ,[fiscal_year_month]
      ,[Commodity]
      ,[commodity_uom]
      ,[category]
      ,[Sub-Category]
      ,[article]
      ,[article_description]
      ,[Brand_Name]
      ,[material]
      ,[color]
      ,[Count]
      ,[size]
      ,[vendor_name]
      ,[Template_URL]
      ,[country_of_origin]
      ,[cost_category_group]
      ,[cost_category]
      ,[cost_element]
      ,[Index_Ticker]
      ,[actual_cost]
      ,[should_cost]
      ,[flag_modelled_cost]
      ,[funding_pct]
      ,[Sales Quantity]
      ,[Avg Unit Retail]
      ,[forecast_anual_unit_volume]
      ,[forecast_COGS]
      ,[forecast_revenue]
      ,[commodity_value]
	  ,filtering_id
	  FROM viz.should_cost_analysis_app;
